#!/bin/bash
read -n1 -p "Production (0) OR Development (1)? [0,1]" input 
case $input in  
  0) cd ../;
    APP_NAME="application";
    SERVER_ADRS="123.12.123.123";
    SERVER_PASS='passphrase';
    DOCKER_CMDS="cd $APP_NAME; docker-compose -f production.yml down";
    sshpass -p "$SERVER_PASS" rsync -avz --exclude-from=$APP_NAME/exclude.txt $APP_NAME/ root@$SERVER_ADRS:/root/$APP_NAME/;
    sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no root@$SERVER_ADRS "$DOCKER_CMDS" ;; 
  1) docker-compose -f local.yml down ;; 
  *) echo INVALID INPUT. ONLY 0 OR 1 ARE VALID. ;; 
esac